// components/Footer.tsx
import { useState } from "react";
import { DottedBackground } from "./DottedBackground";
import { useLanguage } from "../contexts/LanguageContext";

export function Footer() {
  const [selectedOption, setSelectedOption] = useState<
    string | null
  >(null);
  const { t } = useLanguage();

  const options = [
    { id: "terms", text: t("footer.terms"), color: "#FF6B9D" },
    {
      id: "privacy",
      text: t("footer.privacy"),
      color: "#FFEB3B",
    },
    {
      id: "support",
      text: t("footer.support"),
      color: "#2DD4BF",
    },
  ];

  return (
    <div className="text-center relative overflow-hidden pt-[10px] pr-[0px] pb-[40px] pl-[0px]">
      {/* Comic-style dotted background */}
      <DottedBackground />

      <p className="text-[rgb(0,0,0)] mb-6 text-[32px] font-bold relative z-10">
        {t("footer.question")}
      </p>

      <div className="flex justify-center gap-4 flex-wrap relative z-10">
        {options.map((option) => (
          <button
            key={option.id}
            onClick={() => {
              setSelectedOption(option.id);
              // Simulate feedback submission
              setTimeout(() => {
                alert(`${option.text}`);
              }, 100);
            }}
            className="relative group cursor-pointer"
          >
            <div className="absolute inset-0 bg-black rounded-full translate-x-1.5 translate-y-1.5"></div>
            <div
              className="relative rounded-full px-6 py-3 border-4 border-black transition-transform group-hover:translate-x-1 group-hover:translate-y-1 flex items-center gap-3"
              style={{
                backgroundColor:
                  selectedOption === option.id
                    ? option.color
                    : option.color,
                letterSpacing: "0.05em",
                fontWeight: "700",
              }}
            >
              <span>{option.text}</span>
              <svg
                width="24"
                height="24"
                viewBox="0 0 32 32"
                fill="none"
              >
                <path
                  d="M8 16H24M24 16L18 10M24 16L18 22"
                  stroke="black"
                  strokeWidth="3"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </div>
          </button>
        ))}
      </div>
    </div>
  );
}

// src/app/components/footer/footer.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LanguageService } from '../../services/language.service';
import { DottedBackgroundComponent } from '../shared/dotted-background/dotted-background.component';
import { Subject, takeUntil } from 'rxjs';

interface FooterOption {
  id: string;
  text: string;
  color: string;
}

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule, DottedBackgroundComponent],
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent implements OnInit, OnDestroy {
  question = '';
  options: FooterOption[] = [];
  selectedOption: string | null = null;
  private destroy$ = new Subject<void>();

  constructor(public languageService: LanguageService) {}

  ngOnInit() {
    this.languageService.language$.pipe(takeUntil(this.destroy$)).subscribe(() => {
      this.updateTranslations();
    });
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }

  updateTranslations() {
    this.question = this.languageService.t('footer.question');
    
    this.options = [
      { 
        id: 'terms', 
        text: this.languageService.t('footer.terms'), 
        color: '#FF6B9D' 
      },
      {
        id: 'privacy',
        text: this.languageService.t('footer.privacy'),
        color: '#FFEB3B'
      },
      {
        id: 'support',
        text: this.languageService.t('footer.support'),
        color: '#2DD4BF'
      }
    ];
  }

  handleClick(option: FooterOption) {
    this.selectedOption = option.id;
    setTimeout(() => {
      alert(option.text);
    }, 100);
  }
}









<div class="text-center relative overflow-hidden pt-[10px] pr-[0px] pb-[40px] pl-[0px]">
  <!-- Comic-style dotted background -->
  <app-dotted-background></app-dotted-background>

  <p class="text-[rgb(0,0,0)] mb-6 text-[32px] font-bold relative z-10">
    {{ question }}
  </p>

  <div class="flex justify-center gap-4 flex-wrap relative z-10">
    <button
      *ngFor="let option of options"
      (click)="handleClick(option)"
      class="relative group cursor-pointer"
    >
      <div class="absolute inset-0 bg-black rounded-full translate-x-1.5 translate-y-1.5"></div>
      <div
        class="relative rounded-full px-6 py-3 border-4 border-black transition-transform group-hover:translate-x-1 group-hover:translate-y-1 flex items-center gap-3"
        [style.background-color]="option.color"
        style="letter-spacing: 0.05em; font-weight: 700"
      >
        <span>{{ option.text }}</span>
        <svg
          width="24"
          height="24"
          viewBox="0 0 32 32"
          fill="none"
        >
          <path
            d="M8 16H24M24 16L18 10M24 16L18 22"
            stroke="black"
            stroke-width="3"
            stroke-linecap="round"
            stroke-linejoin="round"
          />
        </svg>
      </div>
    </button>
  </div>
</div>
