// components/Hero.tsx
import logo from "figma:asset/30800917f8cc48afda576124e952fbfa1d74411a.png";
import burstBackground from "figma:asset/ba0386384dd64eadcc1260e011229e785c57eb86.png";
import { useLanguage } from '../contexts/LanguageContext';

export function Hero() {
  const { t } = useLanguage();
  
  return (
    <div className="text-center relative overflow-hidden h-[70vh] flex flex-col justify-center items-center mt-[80px]">
      {/* Radial burst background */}
      <div
        className="absolute inset-0 pointer-events-none"
        style={{
          backgroundImage: `url(${burstBackground})`,
          backgroundSize: "cover",
          backgroundPosition: "center",
          backgroundRepeat: "no-repeat",
        }}
      />

      {/* Content */}
      <div className="relative z-10 flex flex-col items-center gap-3">
        {/* Logo */}
        <div className="relative inline-block">
          <img
            src={logo}
            alt="Care Buddy Logo"
            className="w-[500px] h-auto rounded-[0px] max-w-[90vw]"
          />
        </div>

        {/* Text */}
        <p className="text-[rgb(0,0,0)] max-w-md m-[0px] text-[32px] font-bold px-4">
          {t('hero.tagline')}
        </p>

        {/* Action buttons */}
        <div className="flex gap-6 justify-center items-center flex-wrap px-4">
          <button className="relative group cursor-pointer" onClick={() => window.open('https://www.google.com/', '_blank')}>
            <div className="absolute inset-0 bg-black rounded-2xl translate-x-1.5 translate-y-1.5"></div>
            <div className="relative bg-[#FF6B9D] rounded-2xl px-8 py-4 flex items-center gap-3 border-4 border-black transition-transform group-hover:translate-x-1 group-hover:translate-y-1">
              <span
                style={{
                  fontSize: "1.25rem",
                  letterSpacing: "0.05em",
                  fontWeight: "700",
                }}
              >
                {t('hero.seekCare')}
              </span>
              <svg
                width="32"
                height="32"
                viewBox="0 0 32 32"
                fill="none"
              >
                <path
                  d="M8 16H24M24 16L18 10M24 16L18 22"
                  stroke="black"
                  strokeWidth="3"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </div>
          </button>

          <button className="relative group cursor-pointer" onClick={() => window.open('https://www.google.com/', '_blank')}>
            <div className="absolute inset-0 bg-black rounded-2xl translate-x-1.5 translate-y-1.5"></div>
            <div className="relative bg-[#2DD4BF] rounded-2xl px-8 py-4 flex items-center gap-3 border-4 border-black transition-transform group-hover:translate-x-1 group-hover:translate-y-1">
              <span
                style={{
                  fontSize: "1.25rem",
                  letterSpacing: "0.05em",
                  fontWeight: "700",
                }}
              >
                {t('hero.giveCare')}
              </span>
              <svg
                width="32"
                height="32"
                viewBox="0 0 32 32"
                fill="none"
              >
                <path
                  d="M8 16H24M24 16L18 10M24 16L18 22"
                  stroke="black"
                  strokeWidth="3"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </div>
          </button>
        </div>
      </div>
    </div>
  );
}

// src/app/components/hero/hero.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LanguageService } from '../../services/language.service';
import { Subject, takeUntil } from 'rxjs';

@Component({
  selector: 'app-hero',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './hero.component.html',
  styleUrls: ['./hero.component.css']
})
export class HeroComponent implements OnInit, OnDestroy {
  tagline = '';
  seekCare = '';
  giveCare = '';
  private destroy$ = new Subject<void>();

  // You would need to add these images to src/assets folder
  logoUrl = 'assets/logo.png';
  burstBackgroundUrl = 'assets/burst-background.png';

  constructor(public languageService: LanguageService) {}

  ngOnInit() {
    this.languageService.language$.pipe(takeUntil(this.destroy$)).subscribe(() => {
      this.updateTranslations();
    });
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }

  updateTranslations() {
    this.tagline = this.languageService.t('hero.tagline');
    this.seekCare = this.languageService.t('hero.seekCare');
    this.giveCare = this.languageService.t('hero.giveCare');
  }

  openSeekCare() {
    window.open('https://www.google.com/', '_blank');
  }

  openGiveCare() {
    window.open('https://www.google.com/', '_blank');
  }
}









<div class="text-center relative overflow-hidden h-[60vh] md:h-[70vh] flex flex-col justify-center items-center mt-16 md:mt-20">
  <!-- Radial burst background -->
  <div
    class="absolute inset-0 pointer-events-none"
    [style.background-image]="'url(' + burstBackgroundUrl + ')'"
    style="background-size: cover; background-position: center; background-repeat: no-repeat"
  ></div>

  <!-- Content -->
  <div class="relative z-10 flex flex-col items-center gap-2 md:gap-3">
    <!-- Logo -->
    <div class="relative inline-block">
      <img
        [src]="logoUrl"
        alt="Care Buddy Logo"
        class="w-[280px] md:w-[400px] lg:w-[500px] h-auto rounded-[0px] max-w-[90vw]"
      />
    </div>

    <!-- Text -->
    <p class="text-[rgb(0,0,0)] max-w-md m-[0px] text-xl md:text-2xl lg:text-[32px] font-bold px-4">
      {{ tagline }}
    </p>

    <!-- Action buttons -->
    <div class="flex gap-3 md:gap-6 justify-center items-center flex-wrap px-4">
      <button class="relative group cursor-pointer" (click)="openSeekCare()">
        <div class="absolute inset-0 bg-black rounded-xl md:rounded-2xl translate-x-1 translate-y-1 md:translate-x-1.5 md:translate-y-1.5"></div>
        <div class="relative bg-[#FF6B9D] rounded-xl md:rounded-2xl px-4 py-2.5 md:px-8 md:py-4 flex items-center gap-2 md:gap-3 border-2 md:border-4 border-black transition-transform group-hover:translate-x-1 group-hover:translate-y-1">
          <span
            class="text-sm md:text-base lg:text-xl"
            style="letter-spacing: 0.05em; font-weight: 700"
          >
            {{ seekCare }}
          </span>
          <svg
            class="w-5 h-5 md:w-6 md:h-6 lg:w-8 lg:h-8"
            viewBox="0 0 32 32"
            fill="none"
          >
            <path
              d="M8 16H24M24 16L18 10M24 16L18 22"
              stroke="black"
              stroke-width="3"
              stroke-linecap="round"
              stroke-linejoin="round"
            />
          </svg>
        </div>
      </button>

      <button class="relative group cursor-pointer" (click)="openGiveCare()">
        <div class="absolute inset-0 bg-black rounded-xl md:rounded-2xl translate-x-1 translate-y-1 md:translate-x-1.5 md:translate-y-1.5"></div>
        <div class="relative bg-[#2DD4BF] rounded-xl md:rounded-2xl px-4 py-2.5 md:px-8 md:py-4 flex items-center gap-2 md:gap-3 border-2 md:border-4 border-black transition-transform group-hover:translate-x-1 group-hover:translate-y-1">
          <span
            class="text-sm md:text-base lg:text-xl"
            style="letter-spacing: 0.05em; font-weight: 700"
          >
            {{ giveCare }}
          </span>
          <svg
            class="w-5 h-5 md:w-6 md:h-6 lg:w-8 lg:h-8"
            viewBox="0 0 32 32"
            fill="none"
          >
            <path
              d="M8 16H24M24 16L18 10M24 16L18 22"
              stroke="black"
              stroke-width="3"
              stroke-linecap="round"
              stroke-linejoin="round"
            />
          </svg>
        </div>
      </button>
    </div>
  </div>
</div>
