// components/Stats.tsx
import { useState } from "react";
import svgPaths from "../imports/svg-uuz93z7oy3";

const stats = [
  { value: "500+", label: "Zorgverstrekkers" },
  { value: "2.000+", label: "Matches gemaakt" },
  { value: "<2h", label: "Response tijd" },
  { value: "98%", label: "Kwaliteitscore" },
];

export function Stats() {
  const [hoveredIndex, setHoveredIndex] = useState<
    number | null
  >(null);

  return (
    <div
      className="border-t-[3px] border-b-[3px] border-black py-8 relative overflow-hidden"
      style={{
        backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 308 308'%3E%3Cpath d='${encodeURIComponent(svgPaths.p1dafdd00)}' fill='%23F26F8D' fill-opacity='0.4'/%3E%3C/svg%3E")`,
        backgroundSize: "308px 308px",
        backgroundRepeat: "repeat",
      }}
    >
      <div className="grid grid-cols-2 md:grid-cols-4 gap-6 relative z-10">
        {stats.map((stat, index) => {
          const colors = [
            "#FF1493",
            "#4ADE80",
            "#FCD34D",
            "#2DD4BF",
          ];
          const color = colors[index];

          return (
            <div
              key={index}
              className="text-center transition-all duration-300"
              style={{
                transform:
                  hoveredIndex === index
                    ? "scale(1.05)"
                    : "scale(1)",
              }}
              onMouseEnter={() => setHoveredIndex(index)}
              onMouseLeave={() => setHoveredIndex(null)}
            >
              <div
                style={{
                  fontSize: "3.5rem",
                  color: color,
                  letterSpacing: "0.02em",
                  textShadow: "3px 3px 0px rgb(0,0,0)",
                  lineHeight: "1",
                  marginBottom: "0.5rem",
                  fontWeight: "700",
                }}
              >
                {stat.value}
              </div>
              <div
                className="text-black uppercase"
                style={{
                  fontSize: "0.7rem",
                  fontWeight: "700",
                  letterSpacing: "0.08em",
                }}
              >
                {stat.label}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

// src/app/components/stats/stats.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DottedBackgroundComponent } from '../shared/dotted-background/dotted-background.component';

interface Stat {
  value: string;
  label: string;
  color: string;
}

@Component({
  selector: 'app-stats',
  standalone: true,
  imports: [CommonModule, DottedBackgroundComponent],
  templateUrl: './stats.component.html',
  styleUrls: ['./stats.component.css']
})
export class StatsComponent {
  hoveredIndex: number | null = null;

  stats: Stat[] = [
    { value: '500+', label: 'Zorgverstrekkers', color: '#FF1493' },
    { value: '2.000+', label: 'Matches gemaakt', color: '#4ADE80' },
    { value: '<2h', label: 'Response tijd', color: '#FCD34D' },
    { value: '98%', label: 'Kwaliteitscore', color: '#2DD4BF' }
  ];

  getStatStyle(stat: Stat, index: number) {
    return {
      'color': stat.color,
      'letter-spacing': '0.02em',
      'line-height': '1',
      'font-weight': '700'
    };
  }

  getTransform(index: number) {
    return this.hoveredIndex === index ? 'scale(1.05)' : 'scale(1)';
  }

  setHoveredIndex(index: number | null) {
    this.hoveredIndex = index;
  }
}




<div
  class="border-t-[3px] border-b-[3px] border-black py-4 md:py-8 relative overflow-hidden px-4"
>
  <app-dotted-background></app-dotted-background>
  <div class="grid grid-cols-2 md:grid-cols-4 gap-3 md:gap-6 relative z-10">
    <div
      *ngFor="let stat of stats; let i = index"
      class="text-center transition-all duration-300"
      [style.transform]="getTransform(i)"
      (mouseenter)="setHoveredIndex(i)"
      (mouseleave)="setHoveredIndex(null)"
    >
      <div 
        [ngStyle]="getStatStyle(stat, i)"
        class="stat-value text-[2rem] md:text-[3.5rem] mb-1 md:mb-2"
      >
        {{ stat.value }}
      </div>
      <div
        class="text-black uppercase text-xs md:text-[0.7rem]"
        style="font-weight: 700; letter-spacing: 0.08em"
      >
        {{ stat.label }}
      </div>
    </div>
  </div>
</div>
