// components/Transparantie.tsx
import Group from "../imports/Group";
import { DottedBackground } from "./DottedBackground";
import { useLanguage } from "../contexts/LanguageContext";

export function Transparantie() {
  const { t } = useLanguage();
  
  return (
    <div className="pb-12 border-b-4 border-black relative overflow-hidden m-[0px]">
      {/* Comic-style dotted background */}
      <DottedBackground />
      
      <div className="flex justify-center mb-[24px] relative z-10 mt-[45px] mx-4">
        <div className="relative inline-flex items-center">
          <button
            className="bg-[#2DD4BF] text-black px-8 py-3 md:px-12 md:py-4.5 rounded-full border-4 md:border-6 border-black hover:bg-cyan-500 transition-colors uppercase tracking-wide text-base md:text-xl"
            style={{
              fontWeight: "700",
              boxShadow: "6px 6px 0px 0px rgba(0, 0, 0, 1)",
            }}
          >
            {t('protection.title')}
          </button>
          {/* Pink burst decoration */}
          <div className="hidden md:block absolute -right-[60px] -top-9 w-24 h-18 pointer-events-none rotate-[30deg]">
            <Group />
          </div>
        </div>
      </div>

      <div className="space-y-6 max-w-4xl mx-4 md:mx-auto relative z-10">
        {/* PROFESSIONELE VERIFICATIE */}
        <div className="bg-white rounded-2xl md:rounded-3xl border-4 border-black p-4 md:p-8" style={{ boxShadow: "6px 6px 0px 0px rgba(0, 0, 0, 1)" }}>
          <div className="mb-3 md:mb-4 px-3 py-1.5 md:px-6 md:py-2 rounded-full border-2 border-black bg-[#FF6B9D] inline-block uppercase text-xs md:text-sm" style={{ 
            fontWeight: "700",
            backgroundImage: "repeating-linear-gradient(45deg, transparent, transparent 2px, rgba(0,0,0,0.05) 2px, rgba(0,0,0,0.05) 4px)"
          }}>
            {t('protection.verification.title')}
          </div>
          <p className="text-black uppercase tracking-wide text-xs md:text-sm" style={{ fontWeight: "700" }}>
            {t('protection.verification.desc')}
          </p>
        </div>

        {/* GEGEVENSBESCHERMING & GDPR */}
        <div className="bg-white rounded-2xl md:rounded-3xl border-4 border-black p-4 md:p-8" style={{ boxShadow: "6px 6px 0px 0px rgba(0, 0, 0, 1)" }}>
          <div className="mb-3 md:mb-4 px-3 py-1.5 md:px-6 md:py-2 rounded-full border-2 border-black bg-[#FFEB3B] inline-block uppercase text-xs md:text-sm" style={{ 
            fontWeight: "700",
            backgroundImage: "repeating-linear-gradient(45deg, transparent, transparent 2px, rgba(0,0,0,0.05) 2px, rgba(0,0,0,0.05) 4px)"
          }}>
            {t('protection.gdpr.title')}
          </div>
          <p className="text-black uppercase tracking-wide mb-3 md:mb-4 text-xs md:text-sm" style={{ fontWeight: "700" }}>
            {t('protection.gdpr.subtitle')}
          </p>
          <ul className="space-y-2 text-black uppercase tracking-wide text-xs md:text-sm" style={{ fontWeight: "700" }}>
            <li className="flex items-start">
              <span className="mr-2">•</span>
              <span className="font-bold">{t('protection.gdpr.item1')}</span>
            </li>
            <li className="flex items-start">
              <span className="mr-2">•</span>
              <span className="font-bold">{t('protection.gdpr.item2')}</span>
            </li>
            <li className="flex items-start">
              <span className="mr-2">•</span>
              <span className="font-bold">{t('protection.gdpr.item3')}</span>
            </li>
            <li className="flex items-start">
              <span className="mr-2">•</span>
              <span className="font-bold">{t('protection.gdpr.item4')}</span>
            </li>
          </ul>
        </div>

        {/* DUIDELIJKE AANSPRAKELIJKHEIDSPOSITIONERING */}
        <div className="bg-white rounded-2xl md:rounded-3xl border-4 border-black p-4 md:p-8" style={{ boxShadow: "6px 6px 0px 0px rgba(0, 0, 0, 1)" }}>
          <div className="mb-3 md:mb-4 px-3 py-1.5 md:px-6 md:py-2 rounded-full border-2 border-black bg-[#2DD4BF] inline-block uppercase text-xs md:text-sm" style={{ 
            fontWeight: "700",
            backgroundImage: "repeating-linear-gradient(45deg, transparent, transparent 2px, rgba(0,0,0,0.05) 2px, rgba(0,0,0,0.05) 4px)"
          }}>
            {t('protection.liability.title')}
          </div>
          <p className="text-black uppercase tracking-wide text-xs md:text-sm" style={{ fontWeight: "700" }}>
            {t('protection.liability.desc')}
          </p>
        </div>
      </div>
    </div>
  );
}

// src/app/components/transparantie/transparantie.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LanguageService } from '../../services/language.service';
import { DottedBackgroundComponent } from '../shared/dotted-background/dotted-background.component';
import { GroupComponent } from '../shared/group/group.component';
import { Subject, takeUntil } from 'rxjs';

@Component({
  selector: 'app-transparantie',
  standalone: true,
  imports: [CommonModule, DottedBackgroundComponent, GroupComponent],
  templateUrl: './transparantie.component.html',
  styleUrls: ['./transparantie.component.css']
})
export class TransparantieComponent implements OnInit, OnDestroy {
  title = '';
  verification: any = {};
  gdpr: any = {};
  liability: any = {};
  private destroy$ = new Subject<void>();

  constructor(public languageService: LanguageService) {}

  ngOnInit() {
    this.languageService.language$.pipe(takeUntil(this.destroy$)).subscribe(() => {
      this.updateTranslations();
    });
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }

  updateTranslations() {
    this.title = this.languageService.t('protection.title');
    
    this.verification = {
      title: this.languageService.t('protection.verification.title'),
      desc: this.languageService.t('protection.verification.desc')
    };

    this.gdpr = {
      title: this.languageService.t('protection.gdpr.title'),
      subtitle: this.languageService.t('protection.gdpr.subtitle'),
      items: [
        this.languageService.t('protection.gdpr.item1'),
        this.languageService.t('protection.gdpr.item2'),
        this.languageService.t('protection.gdpr.item3'),
        this.languageService.t('protection.gdpr.item4')
      ]
    };

    this.liability = {
      title: this.languageService.t('protection.liability.title'),
      desc: this.languageService.t('protection.liability.desc')
    };
  }
}




<div class="pb-12 border-b-4 border-black relative overflow-hidden m-[0px]">
  <!-- Comic-style dotted background -->
  <app-dotted-background></app-dotted-background>
  
  <div class="flex justify-center mb-[24px] relative z-10 mt-[45px] mx-4">
    <div class="relative inline-flex items-center">
      <button
        class="bg-[#2DD4BF] text-black px-8 py-3 md:px-12 md:py-4.5 rounded-full border-4 md:border-6 border-black hover:bg-cyan-500 transition-colors uppercase tracking-wide text-base md:text-xl"
        style="font-weight: 700; box-shadow: 6px 6px 0px 0px rgba(0, 0, 0, 1)"
      >
        {{ title }}
      </button>
      <div class="hidden md:block absolute -right-[60px] -top-9 w-24 h-18 pointer-events-none rotate-[30deg]">
        <app-group-icon></app-group-icon>
      </div>
    </div>
  </div>

  <div class="space-y-6 max-w-4xl mx-4 md:mx-auto relative z-10">
    <!-- PROFESSIONELE VERIFICATIE -->
    <div class="bg-white rounded-2xl md:rounded-3xl border-4 border-black p-4 md:p-8" style="box-shadow: 6px 6px 0px 0px rgba(0, 0, 0, 1)">
      <div 
        class="mb-3 md:mb-4 px-3 py-1.5 md:px-6 md:py-2 rounded-full border-2 border-black bg-[#FF6B9D] inline-block uppercase text-xs md:text-sm" 
        style="font-weight: 700; background-image: repeating-linear-gradient(45deg, transparent, transparent 2px, rgba(0,0,0,0.05) 2px, rgba(0,0,0,0.05) 4px)"
      >
        {{ verification.title }}
      </div>
      <p class="text-black uppercase tracking-wide text-xs md:text-sm" style="font-weight: 700">
        {{ verification.desc }}
      </p>
    </div>

    <!-- GEGEVENSBESCHERMING & GDPR -->
    <div class="bg-white rounded-2xl md:rounded-3xl border-4 border-black p-4 md:p-8" style="box-shadow: 6px 6px 0px 0px rgba(0, 0, 0, 1)">
      <div 
        class="mb-3 md:mb-4 px-3 py-1.5 md:px-6 md:py-2 rounded-full border-2 border-black bg-[#FFEB3B] inline-block uppercase text-xs md:text-sm" 
        style="font-weight: 700; background-image: repeating-linear-gradient(45deg, transparent, transparent 2px, rgba(0,0,0,0.05) 2px, rgba(0,0,0,0.05) 4px)"
      >
        {{ gdpr.title }}
      </div>
      <p class="text-black uppercase tracking-wide mb-3 md:mb-4 text-xs md:text-sm" style="font-weight: 700">
        {{ gdpr.subtitle }}
      </p>
      <ul class="space-y-2 text-black uppercase tracking-wide text-xs md:text-sm" style="font-weight: 700">
        <li *ngFor="let item of gdpr.items" class="flex items-start">
          <span class="mr-2">•</span>
          <span class="font-bold">{{ item }}</span>
        </li>
      </ul>
    </div>

    <!-- DUIDELIJKE AANSPRAKELIJKHEIDSPOSITIONERING -->
    <div class="bg-white rounded-2xl md:rounded-3xl border-4 border-black p-4 md:p-8" style="box-shadow: 6px 6px 0px 0px rgba(0, 0, 0, 1)">
      <div 
        class="mb-3 md:mb-4 px-3 py-1.5 md:px-6 md:py-2 rounded-full border-2 border-black bg-[#2DD4BF] inline-block uppercase text-xs md:text-sm" 
        style="font-weight: 700; background-image: repeating-linear-gradient(45deg, transparent, transparent 2px, rgba(0,0,0,0.05) 2px, rgba(0,0,0,0.05) 4px)"
      >
        {{ liability.title }}
      </div>
      <p class="text-black uppercase tracking-wide text-xs md:text-sm" style="font-weight: 700">
        {{ liability.desc }}
      </p>
    </div>
  </div>
</div>
