// src/app/components/hoe-werkt-het/hoe-werkt-het.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LanguageService } from '../../services/language.service';
import { DottedBackgroundComponent } from '../shared/dotted-background/dotted-background.component';
import { GroupComponent } from '../shared/group/group.component';
import { Subject, takeUntil } from 'rxjs';

interface Buddy {
  name: string;
  color: string;
  icon: string;
  image: string;
}

@Component({
  selector: 'app-hoe-werkt-het',
  standalone: true,
  imports: [CommonModule, DottedBackgroundComponent, GroupComponent],
  templateUrl: './hoe-werkt-het.component.html',
  styleUrls: ['./hoe-werkt-het.component.css']
})
export class HoeWerktHetComponent implements OnInit, OnDestroy {
  title = '';
  subtitle = '';
  buddies: Buddy[] = [];
  selectedBuddy: number | null = null;
  private destroy$ = new Subject<void>();

  // You would need to add these images to src/assets folder
  firstBlockImage = 'assets/first-block.png';
  secondBlockImage = 'assets/second-block.png';
  thirdBlockImage = 'assets/third-block.png';

  constructor(public languageService: LanguageService) {}

  ngOnInit() {
    this.languageService.language$.pipe(takeUntil(this.destroy$)).subscribe(() => {
      this.updateTranslations();
    });
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }

  updateTranslations() {
    this.title = this.languageService.t('howItWorks.title');
    this.subtitle = this.languageService.t('howItWorks.subtitle');
    this.buddies = [
      {
        name: this.languageService.t('howItWorks.step1'),
        color: '#FF6B9D',
        icon: '📋',
        image: this.firstBlockImage
      },
      {
        name: this.languageService.t('howItWorks.step2'),
        color: '#FFEB3B',
        icon: '✨',
        image: this.secondBlockImage
      },
      {
        name: this.languageService.t('howItWorks.step3'),
        color: '#2DD4BF',
        icon: '🏡',
        image: this.thirdBlockImage
      }
    ];
  }

  setSelectedBuddy(index: number | null) {
    this.selectedBuddy = index;
  }
}




<div class="pb-12 border-b-4 border-black relative overflow-hidden m-[0px]">
  <!-- Comic-style dotted background -->
  <app-dotted-background></app-dotted-background>

  <div class="flex justify-center mb-[24px] relative z-10 mt-[45px] mx-4">
    <div class="relative inline-flex items-center">
      <button
        class="bg-[#2DD4BF] text-black px-8 py-3 md:px-12 md:py-4.5 rounded-full border-4 md:border-6 border-black hover:bg-cyan-500 transition-colors uppercase tracking-wide text-base md:text-xl"
        style="font-weight: 700; box-shadow: 6px 6px 0px 0px rgba(0, 0, 0, 1)"
      >
        {{ title }}
      </button>
      <div class="hidden md:block absolute -right-[60px] -top-9 w-24 h-18 pointer-events-none rotate-[30deg]">
        <app-group-icon></app-group-icon>
      </div>
    </div>
  </div>

  <p class="flex justify-center text-center text-[rgb(0,0,0)] mb-[24px] max-w-md mx-4 md:mx-auto px-4 text-[32px] mt-[0px] mr-[0px] ml-[0px] font-bold">
    {{ subtitle }}
  </p>

  <div class="grid md:grid-cols-3 gap-6 mx-4 md:mx-8 lg:mx-[100px] my-[0px] relative z-10">
    <div
      *ngFor="let buddy of buddies; let i = index"
      class="transition-all duration-300"
      (click)="setSelectedBuddy(i)"
      (mouseenter)="setSelectedBuddy(i)"
      (mouseleave)="setSelectedBuddy(null)"
    >
      <div
        [class]="'bg-white rounded-2xl border-4 border-black p-4 md:p-6 text-center transition-all duration-300 ' + (selectedBuddy === i ? '-translate-y-2' : '')"
        [style.box-shadow]="selectedBuddy === i ? '8px 8px 0px 0px rgba(0, 0, 0, 1)' : '6px 6px 0px 0px rgba(0, 0, 0, 1)'"
      >
        <div
          class="w-32 h-40 md:w-40 md:h-48 mx-auto mb-4 rounded-2xl border-4 border-black flex items-center justify-center overflow-hidden"
          [style.background-color]="buddy.color"
        >
          <img
            [src]="buddy.image"
            [alt]="buddy.name"
            class="w-full h-full object-cover"
          />
        </div>
        <div
          class="px-3 py-1.5 md:px-4 md:py-2 rounded-full text-sm md:text-base border-2 border-black"
          [style.background-color]="buddy.color"
          style="font-weight: 700"
        >
          {{ buddy.name }}
        </div>
      </div>
    </div>
  </div>
</div>

// components/HoeWerktHet.tsx
import { useState } from "react";
import Group from "../imports/Group";
import { ImageWithFallback } from "./figma/ImageWithFallback";
import firstBlockImage from "figma:asset/76d59315edda09b0c9cd6b86339d8fcbb8d90bce.png";
import secondBlockImage from "figma:asset/c1b56e422e7e6dfb13e1a9f5c089a04643e54863.png";
import thirdBlockImage from "figma:asset/16c59ae60614230e34767ab9722b8973454cb93c.png";
import { DottedBackground } from "./DottedBackground";
import { useLanguage } from "../contexts/LanguageContext";

export function HoeWerktHet() {
  const [selectedBuddy, setSelectedBuddy] = useState<number | null>(null);
  const { t } = useLanguage();

  const buddies = [
    {
      name: t('howItWorks.step1'),
      color: "#FF6B9D",
      icon: "📋",
      image: firstBlockImage,
    },
    {
      name: t('howItWorks.step2'),
      color: "#FFEB3B",
      icon: "✨",
      image: secondBlockImage,
    },
    {
      name: t('howItWorks.step3'),
      color: "#2DD4BF",
      icon: "🏡",
      image: thirdBlockImage,
    },
  ];

  return (
    <div className="pb-12 border-b-4 border-black relative overflow-hidden m-[0px]">
      {/* Comic-style dotted background */}
      <DottedBackground />

      <div className="flex justify-center mb-[24px] relative z-10 mt-[45px] mx-4">
        <div className="relative inline-flex items-center">
          <button
            className="bg-[#2DD4BF] text-black px-8 py-3 md:px-12 md:py-4.5 rounded-full border-4 md:border-6 border-black hover:bg-cyan-500 transition-colors uppercase tracking-wide text-base md:text-xl"
            style={{
              fontWeight: "700",
              boxShadow: "6px 6px 0px 0px rgba(0, 0, 0, 1)",
            }}
          >
            {t('howItWorks.title')}
          </button>
          {/* Pink burst decoration */}
          <div className="hidden md:block absolute -right-[60px] -top-9 w-24 h-18 pointer-events-none rotate-[30deg]">
            <Group />
          </div>
        </div>
      </div>

      <p className="flex justify-center text-center text-[rgb(0,0,0)] mb-[24px] max-w-md mx-4 md:mx-auto px-4 text-[32px] mt-[0px] mr-[0px] ml-[0px] font-bold">
        {t('howItWorks.subtitle')}
      </p>

      <div className="grid md:grid-cols-3 gap-6 mx-4 md:mx-8 lg:mx-[100px] my-[0px] relative z-10">
        {buddies.map((buddy, index) => (
          <div
            key={index}
            className="transition-all duration-300"
            onClick={() => setSelectedBuddy(index)}
            onMouseEnter={() => setSelectedBuddy(index)}
            onMouseLeave={() => setSelectedBuddy(null)}
          >
            <div
              className={`bg-white rounded-2xl border-4 border-black p-4 md:p-6 text-center transition-all duration-300 ${
                selectedBuddy === index ? "-translate-y-2" : ""
              }`}
              style={{
                boxShadow:
                  selectedBuddy === index
                    ? "8px 8px 0px 0px rgba(0, 0, 0, 1)"
                    : "6px 6px 0px 0px rgba(0, 0, 0, 1)",
              }}
            >
              <div
                className="w-32 h-40 md:w-40 md:h-48 mx-auto mb-4 rounded-2xl border-4 border-black flex items-center justify-center overflow-hidden"
                style={{ backgroundColor: buddy.color }}
              >
                <ImageWithFallback
                  src={buddy.image}
                  alt={buddy.name}
                  className="w-full h-full object-cover"
                />
              </div>
              <div
                className="px-3 py-1.5 md:px-4 md:py-2 rounded-full text-sm md:text-base border-2 border-black"
                style={{
                  backgroundColor: buddy.color,
                  fontWeight: "700",
                }}
              >
                {buddy.name}
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
