// components/Navigation.tsx
import { useState } from "react";
import { Menu, X, Globe } from "lucide-react";
import { useLanguage } from "../contexts/LanguageContext";

export function Navigation() {
  const [isOpen, setIsOpen] = useState(false);
  const { language, setLanguage, t } = useLanguage();

  const menuItems = [
    { label: t("nav.whatIsIt"), href: "#wat-is-het" },
    { label: t("nav.howItWorks"), href: "#hoe-werkt-het" },
    { label: t("nav.forWhom"), href: "#voor-wie" },
    { label: t("nav.protected"), href: "#beschermd" },
    { label: t("nav.faq"), href: "#faq" },
    { label: t("nav.support"), href: "#support" },
  ];

  const scrollToSection = (
    e: React.MouseEvent<HTMLAnchorElement>,
    href: string,
  ) => {
    e.preventDefault();
    const element = document.querySelector(href);
    if (element) {
      const navHeight = 80; // Account for fixed nav height
      const elementPosition =
        element.getBoundingClientRect().top;
      const offsetPosition =
        elementPosition + window.pageYOffset - navHeight;

      window.scrollTo({
        top: offsetPosition,
        behavior: "smooth",
      });
      setIsOpen(false);
    }
  };

  const scrollToTop = (
    e: React.MouseEvent<HTMLAnchorElement>,
  ) => {
    e.preventDefault();
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
    setIsOpen(false);
  };

  return (
    <nav className="fixed top-0 left-0 right-0 z-50 bg-white border-b-4 border-black">
      <div className="max-w-7xl mx-auto px-4">
        <div className="flex justify-between items-center h-20">
          {/* Logo/Brand */}
          <a
            href="#top"
            onClick={scrollToTop}
            className="uppercase tracking-wide cursor-pointer hover:opacity-80 transition-opacity"
            style={{ fontWeight: "700", fontSize: "18px" }}
          >
            Care Buddy
          </a>

          {/* Desktop Menu */}
          <div className="hidden md:flex items-center gap-1">
            {menuItems.map((item) => (
              <a
                key={item.href}
                href={item.href}
                onClick={(e) => scrollToSection(e, item.href)}
                className="px-4 py-2 text-black hover:bg-gray-100 rounded-lg transition-colors uppercase tracking-wide text-sm"
                style={{ fontWeight: "400" }}
              >
                {item.label}
              </a>
            ))}
            {/* Language Switcher */}
            <button
              onClick={() =>
                setLanguage(language === "nl" ? "en" : "nl")
              }
              className="ml-2 px-3 py-2 text-black hover:bg-gray-100 rounded-lg transition-colors flex items-center gap-2 border-2 border-black"
              aria-label="Switch language"
            >
              <Globe className="w-4 h-4" strokeWidth={2.5} />
              <span
                className="uppercase text-sm"
                style={{ fontWeight: "700" }}
              >
                {language === "nl" ? "NL" : "EN"}
              </span>
            </button>
          </div>

          {/* Mobile Menu Button & Language Switcher */}
          <div className="md:hidden flex items-center gap-2">
            <button
              onClick={() =>
                setLanguage(language === "nl" ? "en" : "nl")
              }
              className="px-3 py-2 text-black hover:bg-gray-100 rounded-lg transition-colors flex items-center gap-1 border-2 border-black"
              aria-label="Switch language"
            >
              <Globe className="w-4 h-4" strokeWidth={2.5} />
              <span
                className="uppercase text-xs"
                style={{ fontWeight: "700" }}
              >
                {language === "nl" ? "NL" : "EN"}
              </span>
            </button>
            <button
              onClick={() => setIsOpen(!isOpen)}
              className="p-2 rounded-lg hover:bg-gray-100 transition-colors"
              aria-label="Toggle menu"
            >
              {isOpen ? (
                <X className="w-6 h-6" strokeWidth={3} />
              ) : (
                <Menu className="w-6 h-6" strokeWidth={3} />
              )}
            </button>
          </div>
        </div>

        {/* Mobile Menu */}
        {isOpen && (
          <div className="md:hidden py-4 border-t-2 border-black">
            {menuItems.map((item) => (
              <a
                key={item.href}
                href={item.href}
                onClick={(e) => scrollToSection(e, item.href)}
                className="block px-4 py-3 text-black hover:bg-gray-100 transition-colors uppercase tracking-wide text-sm"
                style={{ fontWeight: "400" }}
              >
                {item.label}
              </a>
            ))}
          </div>
        )}
      </div>
    </nav>
  );
}

// src/app/components/navigation/navigation.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LanguageService, Language } from '../../services/language.service';
import { Subject, takeUntil } from 'rxjs';

@Component({
  selector: 'app-navigation',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './navigation.component.html',
  styleUrls: ['./navigation.component.css']
})
export class NavigationComponent implements OnInit, OnDestroy {
  isOpen = false;
  language: Language = 'nl';
  private destroy$ = new Subject<void>();
  
  menuItems: Array<{ label: string; href: string }> = [];

  constructor(public languageService: LanguageService) {}

  ngOnInit() {
    this.languageService.language$.pipe(takeUntil(this.destroy$)).subscribe(lang => {
      this.language = lang;
      this.updateMenuItems();
    });
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }

  updateMenuItems() {
    this.menuItems = [
      { label: this.languageService.t("nav.whatIsIt"), href: "#wat-is-het" },
      { label: this.languageService.t("nav.howItWorks"), href: "#hoe-werkt-het" },
      { label: this.languageService.t("nav.forWhom"), href: "#voor-wie" },
      { label: this.languageService.t("nav.protected"), href: "#beschermd" },
      { label: this.languageService.t("nav.faq"), href: "#faq" },
      { label: this.languageService.t("nav.support"), href: "#support" },
    ];
  }

  scrollToSection(event: Event, href: string) {
    event.preventDefault();
    const element = document.querySelector(href);
    if (element) {
      const navHeight = 80;
      const elementPosition = element.getBoundingClientRect().top;
      const offsetPosition = elementPosition + window.pageYOffset - navHeight;

      window.scrollTo({
        top: offsetPosition,
        behavior: 'smooth'
      });
      this.isOpen = false;
    }
  }

  scrollToTop(event: Event) {
    event.preventDefault();
    window.scrollTo({
      top: 0,
      behavior: 'smooth'
    });
    this.isOpen = false;
  }

  toggleLanguage() {
    const newLang: Language = this.language === 'nl' ? 'en' : 'nl';
    this.languageService.setLanguage(newLang);
  }

  toggleMenu() {
    this.isOpen = !this.isOpen;
  }
}









<nav class="fixed top-0 left-0 right-0 z-50 bg-white border-b-4 border-black">
  <div class="max-w-7xl mx-auto px-4">
    <div class="flex justify-between items-center h-20">
      <!-- Logo/Brand -->
      <a
        href="#top"
        (click)="scrollToTop($event)"
        class="uppercase tracking-wide cursor-pointer hover:opacity-80 transition-opacity"
        style="font-weight: 700; font-size: 18px"
      >
        Care Buddy
      </a>

      <!-- Desktop Menu -->
      <div class="hidden md:flex items-center gap-1">
        <a
          *ngFor="let item of menuItems"
          [href]="item.href"
          (click)="scrollToSection($event, item.href)"
          class="px-4 py-2 text-black hover:bg-gray-100 rounded-lg transition-colors uppercase tracking-wide text-sm"
          style="font-weight: 400"
        >
          {{ item.label }}
        </a>
        <!-- Language Switcher -->
        <button
          (click)="toggleLanguage()"
          class="ml-2 px-3 py-2 text-black hover:bg-gray-100 rounded-lg transition-colors flex items-center gap-2 border-2 border-black"
          aria-label="Switch language"
        >
          <svg
            class="w-4 h-4"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            stroke-width="2.5"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M12 21a9.004 9.004 0 008.716-6.747M12 21a9.004 9.004 0 01-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 017.843 4.582M12 3a8.997 8.997 0 00-7.843 4.582m15.686 0A11.953 11.953 0 0112 10.5c-2.998 0-5.74-1.1-7.843-2.918m15.686 0A8.959 8.959 0 0121 12c0 .778-.099 1.533-.284 2.253m0 0A17.919 17.919 0 0112 16.5c-3.162 0-6.133-.815-8.716-2.247m0 0A9.015 9.015 0 013 12c0-1.605.42-3.113 1.157-4.418"
            />
          </svg>
          <span class="uppercase text-sm" style="font-weight: 700">
            {{ language === 'nl' ? 'NL' : 'EN' }}
          </span>
        </button>
      </div>

      <!-- Mobile Menu Button & Language Switcher -->
      <div class="md:hidden flex items-center gap-2">
        <button
          (click)="toggleLanguage()"
          class="px-3 py-2 text-black hover:bg-gray-100 rounded-lg transition-colors flex items-center gap-1 border-2 border-black"
          aria-label="Switch language"
        >
          <svg
            class="w-4 h-4"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            stroke-width="2.5"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M12 21a9.004 9.004 0 008.716-6.747M12 21a9.004 9.004 0 01-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 017.843 4.582M12 3a8.997 8.997 0 00-7.843 4.582m15.686 0A11.953 11.953 0 0112 10.5c-2.998 0-5.74-1.1-7.843-2.918m15.686 0A8.959 8.959 0 0121 12c0 .778-.099 1.533-.284 2.253m0 0A17.919 17.919 0 0112 16.5c-3.162 0-6.133-.815-8.716-2.247m0 0A9.015 9.015 0 013 12c0-1.605.42-3.113 1.157-4.418"
            />
          </svg>
          <span class="uppercase text-xs" style="font-weight: 700">
            {{ language === 'nl' ? 'NL' : 'EN' }}
          </span>
        </button>
        <button
          (click)="toggleMenu()"
          class="p-2 rounded-lg hover:bg-gray-100 transition-colors"
          aria-label="Toggle menu"
        >
          <svg
            *ngIf="isOpen"
            class="w-6 h-6"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            stroke-width="3"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M6 18L18 6M6 6l12 12"
            />
          </svg>
          <svg
            *ngIf="!isOpen"
            class="w-6 h-6"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            stroke-width="3"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M4 6h16M4 12h16M4 18h16"
            />
          </svg>
        </button>
      </div>
    </div>

    <!-- Mobile Menu -->
    <div *ngIf="isOpen" class="md:hidden py-4 border-t-2 border-black">
      <a
        *ngFor="let item of menuItems"
        [href]="item.href"
        (click)="scrollToSection($event, item.href)"
        class="block px-4 py-3 text-black hover:bg-gray-100 transition-colors uppercase tracking-wide text-sm"
        style="font-weight: 400"
      >
        {{ item.label }}
      </a>
    </div>
  </div>
</nav>
