// components/WaarAan.tsx
import { useState } from "react";
import Group from "../imports/Group";
import { DottedBackground } from "./DottedBackground";
import { useLanguage } from "../contexts/LanguageContext";

const categories = [
  { name: "Huishoudelijke hulp", color: "#FF6B9D" },
  { name: "Administratie", color: "#FFEB3B" },
  { name: "Boodschappen", color: "#2DD4BF" },
];

const items = [
  "Stofzuigen en dweilen",
  "Ramen wassen",
  "Badkamer schoonmaken",
  "Keuken schoonmaken",
  "Strijken",
  "Beddengoed verschonen",
];

export function WaarAan() {
  const [selectedCategory, setSelectedCategory] = useState(0);
  const { t } = useLanguage();

  return (
    <div className="pb-12 border-b-4 border-black relative overflow-hidden m-[0px]">
      {/* Comic-style dotted background */}
      <DottedBackground />

      <div className="flex justify-center mb-[24px] relative z-10 mt-[45px] mx-4">
        <div className="relative inline-flex items-center">
          <button
            className="bg-[#2DD4BF] text-black px-8 py-3 md:px-12 md:py-4.5 rounded-full border-4 md:border-6 border-black hover:bg-cyan-500 transition-colors uppercase tracking-wide text-base md:text-xl"
            style={{
              fontWeight: "700",
              boxShadow: "6px 6px 0px 0px rgba(0, 0, 0, 1)",
            }}
          >
            {t('forWhom.title')}
          </button>
          {/* Pink burst decoration */}
          <div className="hidden md:block absolute -right-[60px] -top-9 w-24 h-18 pointer-events-none rotate-[30deg]">
            <Group />
          </div>
        </div>
      </div>

      <p
        className="text-center text-[rgb(0,0,0)] mb-6 max-w-md mx-4 md:mx-auto px-4 text-[32px]"
        style={{ fontWeight: "700" }}
      >
        {t('forWhom.subtitle')}
      </p>

      <div className="grid md:grid-cols-3 gap-6 mx-4 md:mx-8 lg:mx-[100px] my-[0px] relative z-10">
        {/* ZORGVRAGERS */}
        <div
          className="bg-white rounded-2xl border-4 border-black p-4 md:p-6 flex flex-col"
          style={{
            boxShadow: "6px 6px 0px 0px rgba(0, 0, 0, 1)",
          }}
        >
          <div
            className="mb-3 md:mb-4 px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black bg-[#FF6B9D] text-center uppercase text-sm md:text-base"
            style={{
              fontWeight: "700",
              backgroundImage:
                "repeating-linear-gradient(45deg, transparent, transparent 2px, rgba(0,0,0,0.05) 2px, rgba(0,0,0,0.05) 4px)",
            }}
          >
            {t('forWhom.careRecipients.title')}
          </div>
          <p className="text-sm md:text-base mb-4 text-center md:h-[120px]" style={{ fontWeight: "700" }}>
            {t('forWhom.careRecipients.desc')}
          </p>
          <div className="space-y-2">
            <div className="px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black text-center text-xs md:text-sm" style={{ fontWeight: "700" }}>
              {t('forWhom.careRecipients.item1')}
            </div>
            <div className="px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black text-center text-xs md:text-sm" style={{ fontWeight: "700" }}>
              {t('forWhom.careRecipients.item2')}
            </div>
            <div className="px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black text-center text-xs md:text-sm" style={{ fontWeight: "700" }}>
              {t('forWhom.careRecipients.item3')}
            </div>
            <div className="px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black text-center text-xs md:text-sm" style={{ fontWeight: "700" }}>
              {t('forWhom.careRecipients.item4')}
            </div>
          </div>
        </div>

        {/* ORGANISATIES */}
        <div
          className="bg-white rounded-2xl border-4 border-black p-4 md:p-6 flex flex-col"
          style={{
            boxShadow: "6px 6px 0px 0px rgba(0, 0, 0, 1)",
          }}
        >
          <div
            className="mb-3 md:mb-4 px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black bg-[#FFEB3B] text-center uppercase text-sm md:text-base"
            style={{
              fontWeight: "700",
              backgroundImage:
                "repeating-linear-gradient(45deg, transparent, transparent 2px, rgba(0,0,0,0.05) 2px, rgba(0,0,0,0.05) 4px)",
            }}
          >
            {t('forWhom.organizations.title')}
          </div>
          <p className="text-sm md:text-base mb-4 text-center md:h-[120px]" style={{ fontWeight: "700" }}>
            {t('forWhom.organizations.desc')}
          </p>
          <div className="space-y-2">
            <div className="px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black text-center text-xs md:text-sm" style={{ fontWeight: "700" }}>
              {t('forWhom.organizations.item1')}
            </div>
            <div className="px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black text-center text-xs md:text-sm" style={{ fontWeight: "700" }}>
              {t('forWhom.organizations.item2')}
            </div>
            <div className="px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black text-center text-xs md:text-sm" style={{ fontWeight: "700" }}>
              {t('forWhom.organizations.item3')}
            </div>
            <div className="px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black text-center text-xs md:text-sm" style={{ fontWeight: "700" }}>
              {t('forWhom.organizations.item4')}
            </div>
          </div>
        </div>

        {/* ZORGVERLENER */}
        <div
          className="bg-white rounded-2xl border-4 border-black p-4 md:p-6 flex flex-col"
          style={{
            boxShadow: "6px 6px 0px 0px rgba(0, 0, 0, 1)",
          }}
        >
          <div
            className="mb-3 md:mb-4 px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black bg-[#2DD4BF] text-center uppercase text-sm md:text-base"
            style={{
              fontWeight: "700",
              backgroundImage:
                "repeating-linear-gradient(45deg, transparent, transparent 2px, rgba(0,0,0,0.05) 2px, rgba(0,0,0,0.05) 4px)",
            }}
          >
            {t('forWhom.careProviders.title')}
          </div>
          <p className="text-sm md:text-base mb-4 text-center md:h-[120px]" style={{ fontWeight: "700" }}>
            {t('forWhom.careProviders.desc')}
          </p>
          <div className="space-y-2">
            <div className="px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black text-center text-xs md:text-sm" style={{ fontWeight: "700" }}>
              {t('forWhom.careProviders.item1')}
            </div>
            <div className="px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black text-center text-xs md:text-sm" style={{ fontWeight: "700" }}>
              {t('forWhom.careProviders.item2')}
            </div>
            <div className="px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black text-center text-xs md:text-sm" style={{ fontWeight: "700" }}>
              {t('forWhom.careProviders.item3')}
            </div>
            <div className="px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black text-center text-xs md:text-sm" style={{ fontWeight: "700" }}>
              {t('forWhom.careProviders.item4')}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/app/components/waar-aan/waar-aan.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LanguageService } from '../../services/language.service';
import { DottedBackgroundComponent } from '../shared/dotted-background/dotted-background.component';
import { GroupComponent } from '../shared/group/group.component';
import { Subject, takeUntil } from 'rxjs';

@Component({
  selector: 'app-waar-aan',
  standalone: true,
  imports: [CommonModule, DottedBackgroundComponent, GroupComponent],
  templateUrl: './waar-aan.component.html',
  styleUrls: ['./waar-aan.component.css']
})
export class WaarAanComponent implements OnInit, OnDestroy {
  title = '';
  subtitle = '';
  careRecipients: any = {};
  organizations: any = {};
  careProviders: any = {};
  private destroy$ = new Subject<void>();

  constructor(public languageService: LanguageService) {}

  ngOnInit() {
    this.languageService.language$.pipe(takeUntil(this.destroy$)).subscribe(() => {
      this.updateTranslations();
    });
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }

  updateTranslations() {
    this.title = this.languageService.t('forWhom.title');
    this.subtitle = this.languageService.t('forWhom.subtitle');
    
    this.careRecipients = {
      title: this.languageService.t('forWhom.careRecipients.title'),
      desc: this.languageService.t('forWhom.careRecipients.desc'),
      items: [
        this.languageService.t('forWhom.careRecipients.item1'),
        this.languageService.t('forWhom.careRecipients.item2'),
        this.languageService.t('forWhom.careRecipients.item3'),
        this.languageService.t('forWhom.careRecipients.item4')
      ]
    };

    this.organizations = {
      title: this.languageService.t('forWhom.organizations.title'),
      desc: this.languageService.t('forWhom.organizations.desc'),
      items: [
        this.languageService.t('forWhom.organizations.item1'),
        this.languageService.t('forWhom.organizations.item2'),
        this.languageService.t('forWhom.organizations.item3'),
        this.languageService.t('forWhom.organizations.item4')
      ]
    };

    this.careProviders = {
      title: this.languageService.t('forWhom.careProviders.title'),
      desc: this.languageService.t('forWhom.careProviders.desc'),
      items: [
        this.languageService.t('forWhom.careProviders.item1'),
        this.languageService.t('forWhom.careProviders.item2'),
        this.languageService.t('forWhom.careProviders.item3'),
        this.languageService.t('forWhom.careProviders.item4')
      ]
    };
  }
}




<div class="pb-12 border-b-4 border-black relative overflow-hidden m-[0px]">
  <!-- Comic-style dotted background -->
  <app-dotted-background></app-dotted-background>

  <div class="flex justify-center mb-[24px] relative z-10 mt-[45px] mx-4">
    <div class="relative inline-flex items-center">
      <button
        class="bg-[#2DD4BF] text-black px-8 py-3 md:px-12 md:py-4.5 rounded-full border-4 md:border-6 border-black hover:bg-cyan-500 transition-colors uppercase tracking-wide text-base md:text-xl"
        style="font-weight: 700; box-shadow: 6px 6px 0px 0px rgba(0, 0, 0, 1)"
      >
        {{ title }}
      </button>
      <div class="hidden md:block absolute -right-[60px] -top-9 w-24 h-18 pointer-events-none rotate-[30deg]">
        <app-group-icon></app-group-icon>
      </div>
    </div>
  </div>

  <p
    class="text-center text-[rgb(0,0,0)] mb-6 max-w-md mx-4 md:mx-auto px-4 text-[32px]"
    style="font-weight: 700"
  >
    {{ subtitle }}
  </p>

  <div class="grid md:grid-cols-3 gap-6 mx-4 md:mx-8 lg:mx-[100px] my-[0px] relative z-10">
    <!-- ZORGVRAGERS -->
    <div
      class="bg-white rounded-2xl border-4 border-black p-4 md:p-6 flex flex-col"
      style="box-shadow: 6px 6px 0px 0px rgba(0, 0, 0, 1)"
    >
      <div
        class="mb-3 md:mb-4 px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black bg-[#FF6B9D] text-center uppercase text-sm md:text-base"
        style="font-weight: 700; background-image: repeating-linear-gradient(45deg, transparent, transparent 2px, rgba(0,0,0,0.05) 2px, rgba(0,0,0,0.05) 4px)"
      >
        {{ careRecipients.title }}
      </div>
      <p class="text-sm md:text-base mb-4 text-center md:h-[120px]" style="font-weight: 700">
        {{ careRecipients.desc }}
      </p>
      <div class="space-y-2">
        <div
          *ngFor="let item of careRecipients.items"
          class="px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black text-center text-xs md:text-sm"
          style="font-weight: 700"
        >
          {{ item }}
        </div>
      </div>
    </div>

    <!-- ORGANISATIES -->
    <div
      class="bg-white rounded-2xl border-4 border-black p-4 md:p-6 flex flex-col"
      style="box-shadow: 6px 6px 0px 0px rgba(0, 0, 0, 1)"
    >
      <div
        class="mb-3 md:mb-4 px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black bg-[#FFEB3B] text-center uppercase text-sm md:text-base"
        style="font-weight: 700; background-image: repeating-linear-gradient(45deg, transparent, transparent 2px, rgba(0,0,0,0.05) 2px, rgba(0,0,0,0.05) 4px)"
      >
        {{ organizations.title }}
      </div>
      <p class="text-sm md:text-base mb-4 text-center md:h-[120px]" style="font-weight: 700">
        {{ organizations.desc }}
      </p>
      <div class="space-y-2">
        <div
          *ngFor="let item of organizations.items"
          class="px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black text-center text-xs md:text-sm"
          style="font-weight: 700"
        >
          {{ item }}
        </div>
      </div>
    </div>

    <!-- ZORGVERLENER -->
    <div
      class="bg-white rounded-2xl border-4 border-black p-4 md:p-6 flex flex-col"
      style="box-shadow: 6px 6px 0px 0px rgba(0, 0, 0, 1)"
    >
      <div
        class="mb-3 md:mb-4 px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black bg-[#2DD4BF] text-center uppercase text-sm md:text-base"
        style="font-weight: 700; background-image: repeating-linear-gradient(45deg, transparent, transparent 2px, rgba(0,0,0,0.05) 2px, rgba(0,0,0,0.05) 4px)"
      >
        {{ careProviders.title }}
      </div>
      <p class="text-sm md:text-base mb-4 text-center md:h-[120px]" style="font-weight: 700">
        {{ careProviders.desc }}
      </p>
      <div class="space-y-2">
        <div
          *ngFor="let item of careProviders.items"
          class="px-3 py-1.5 md:px-4 md:py-2 rounded-full border-2 border-black text-center text-xs md:text-sm"
          style="font-weight: 700"
        >
          {{ item }}
        </div>
      </div>
    </div>
  </div>
</div>
